<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="author" content="Andrew Heiss" />


<title>Supporting data and numbers for Chapter 3</title>

<script src="chapter_3_blanks_files/jquery-1.11.0/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="chapter_3_blanks_files/bootstrap-3.3.1/css/flatly.min.css" rel="stylesheet" />
<script src="chapter_3_blanks_files/bootstrap-3.3.1/js/bootstrap.min.js"></script>
<script src="chapter_3_blanks_files/bootstrap-3.3.1/shim/html5shiv.min.js"></script>
<script src="chapter_3_blanks_files/bootstrap-3.3.1/shim/respond.min.js"></script>



<link rel="stylesheet" href="fixes.css" type="text/css" />

</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img { 
  max-width:100%; 
  height: auto; 
}
</style>
<div class="container-fluid main-container">


<div id="header">
<h1 class="title">Supporting data and numbers for Chapter 3</h1>
<h4 class="author"><em>Andrew Heiss</em></h4>
<h4 class="date"><em>January 4, 2016</em></h4>
</div>

<div id="TOC">
<ul>
<li><a href="#countries-receiving-most-aid-through-igos">Countries receiving most aid through IGOs</a><ul>
<li><a href="#actual-text">Actual text</a></li>
</ul></li>
<li><a href="#us-funding-to-ngos">US funding to NGOs</a><ul>
<li><a href="#actual-text-1">Actual text</a></li>
</ul></li>
<li><a href="#stakeholders-with-whom-ngos-discuss-the-tip-report">Stakeholders with whom NGOs discuss the TIP report</a><ul>
<li><a href="#updated-figure-3.4">Updated Figure 3.4</a></li>
</ul></li>
<li><a href="#interactions-with-the-us">Interactions with the US</a><ul>
<li><a href="#actual-text-2">Actual text</a></li>
</ul></li>
<li><a href="#awareness-of-tip-report">Awareness of TIP report</a><ul>
<li><a href="#actual-text-3">Actual text</a></li>
</ul></li>
<li><a href="#tip-use-by-government-officials">TIP use by government officials</a><ul>
<li><a href="#actual-text-4">Actual text</a></li>
</ul></li>
<li><a href="#us-embassy-activity">US embassy activity</a><ul>
<li><a href="#actual-text-5">Actual text</a></li>
</ul></li>
<li><a href="#us-embassy-importance">US embassy importance</a><ul>
<li><a href="#actual-text-6">Actual text</a></li>
</ul></li>
<li><a href="#us-embassy-positivity">US embassy positivity</a><ul>
<li><a href="#actual-text-7">Actual text</a></li>
</ul></li>
<li><a href="#general-survey-details">General survey details</a><ul>
<li><a href="#actual-text-8">Actual text</a></li>
</ul></li>
</ul>
</div>

<div id="countries-receiving-most-aid-through-igos" class="section level1">
<h1>Countries receiving most aid through IGOs</h1>
<pre><code>## 
## ----------------------
##   country     total   
## ----------- ----------
##    India    16,662,345
## 
##  Indonesia  14,909,683
## 
##  Thailand   14,632,904
## 
##   Brazil    12,753,006
## 
##   Ukraine   8,698,789 
## 
##   Mexico    7,853,014 
## 
## Philippines 6,288,313 
## 
##  Cambodia   6,212,012 
## 
##  Tanzania   6,148,325 
## 
##   Uganda    5,791,000 
## ----------------------</code></pre>
<div id="actual-text" class="section level3">
<h3>Actual text</h3>
<blockquote>
<p>The countries that have received most US aid through IGOs are India, Indonesia, Thailand, Brazil, and Ukraine.</p>
</blockquote>
</div>
</div>
<div id="us-funding-to-ngos" class="section level1">
<h1>US funding to NGOs</h1>
<p>Grants given just to NGOs:</p>
<pre><code>## [1] 737</code></pre>
<p>Number of countries receiving grants to NGOs:</p>
<pre><code>## [1] 120</code></pre>
<p>Countries receiving the most grant money for NGOs:</p>
<pre><code>## 
## ----------------------------------------
##            country              total   
## ----------------------------- ----------
##           Indonesia           18,417,946
## 
##           Cambodia            14,928,683
## 
##          Philippines          12,764,782
## 
##             Nepal             12,565,540
## 
##             India             11,856,135
## 
##            Africa             11,328,325
## 
##            Mexico             10,857,275
## 
##            Global             10,525,540
## 
## East Asia and Pacific Islands 9,087,714 
## 
##             Haiti             7,686,850 
## ----------------------------------------</code></pre>
<p>Surveyed NGOs that received funding from the US:</p>
<pre><code>## [1] 90</code></pre>
<div id="actual-text-1" class="section level3">
<h3>Actual text</h3>
<blockquote>
<p>Although the US funding is modest, between 2001-2014, the US funded 737 NGO projects on TIP in 120 of countries. The biggest recipient countries of NGO grants have been Indonesia, Cambodia, the Philippines, Nepal, and India. In the survey of NGOs worldwide, 90 reported having received some sort of funding from the US.</p>
</blockquote>
</div>
</div>
<div id="stakeholders-with-whom-ngos-discuss-the-tip-report" class="section level1">
<h1>Stakeholders with whom NGOs discuss the TIP report</h1>
<div id="updated-figure-3.4" class="section level3">
<h3>Updated Figure 3.4</h3>
<p>This image is saved in Dropbox as <code>figures/fig_stakeholders_discussed.pdf</code> (and <code>.png</code> too).</p>
<p><img src="chapter_3_blanks_files/figure-html/unnamed-chunk-12-1.png" title="" alt="" width="672" /></p>
</div>
</div>
<div id="interactions-with-the-us" class="section level1">
<h1>Interactions with the US</h1>
<p>Number of respondents <em>that don’t work exclusively in the US</em>:</p>
<pre><code>## [1] 480</code></pre>
<p>Proportion of organizations that were involved with the US somehow:</p>
<pre><code>## [1] 0.6833333</code></pre>
<div id="actual-text-2" class="section level3">
<h3>Actual text</h3>
<blockquote>
<p>The global survey found that many NGOs interact extensively with the US embassy or government. More than two thirds of the 480 respondents said they’d engaged in some form with the US government over the last 10-15 years. About half said they had had direct contact with US officials, and about a fifth reported some form of direct cooperation. Another fifth reported receiving direct funding from the US government to facilitate their work.</p>
</blockquote>
<pre><code>## 
## ------------------------------------------------
##      Type of involvement        Responses    %  
## ------------------------------ ----------- -----
##   Direct contact (meetings)        259     48.59
## 
## We have not had any contact or     188     35.27
##      funding from the US                        
## 
##       Direct cooperation           110     20.64
## 
##   Our organization received        101     18.95
##            funding                              
## 
##             Other                  72      13.51
## 
##           Don&#39;t know               32        6  
## ------------------------------------------------</code></pre>
<p>This image is saved in Dropbox as <code>figures/fig_involvement_with_us.pdf</code> (and <code>.png</code> too).</p>
<p><img src="chapter_3_blanks_files/figure-html/unnamed-chunk-16-1.png" title="" alt="" width="672" /></p>
</div>
</div>
<div id="awareness-of-tip-report" class="section level1">
<h1>Awareness of TIP report</h1>
<div id="actual-text-3" class="section level3">
<h3>Actual text</h3>
<blockquote>
<p>One set of questions pertained to the awareness of the TIP report as a measure of the penetration of its message. If the US TIP report is effective in gaining attention around the world, then most TIP NGOs should have at least heard of the report. Indeed, the survey found that 87% of respondents had heard of the annual report.</p>
</blockquote>
</div>
</div>
<div id="tip-use-by-government-officials" class="section level1">
<h1>TIP use by government officials</h1>
<p>Proportion of organization-countries that heard the report used by government officials:</p>
<pre><code>## 
## ---------------------------
##  TIP.used   Freq   Percent 
## ---------- ------ ---------
##     No      265     56.38  
## 
##    Yes      205     43.62  
## ---------------------------</code></pre>
<div id="actual-text-4" class="section level3">
<h3>Actual text</h3>
<blockquote>
<p>To explore this, NGOs were asked if they had ever heard government officials mention the report either publically or in private and were then offered a write-in question about the connection. The results showed that 43.62% of respondents had heard government officials refer to the report in any of the countries they work in. {TODO: STUFF ABOUT REASONS MENTIONED.}</p>
</blockquote>
<p>Reasons the government mentioned the report:</p>
<pre><code>## 
## -----------------------------------------------
##      Reason for mention        Responses    %  
## ----------------------------- ----------- -----
## Assessment purposes, general      49      29.7 
## 
##  Unofficial comments on TIP       36      21.82
## 
##             Other                 21      12.73
## 
##     Negative, against TIP         19      11.52
## 
##     Conferences, meetings         17      10.3 
## 
##       Negative, general           13      7.88 
## 
##   Official comments on TIP,       13      7.88 
##      government context                        
## 
##            Policy                 11      6.67 
## 
##            Efforts                 9      5.45 
## 
##             Media                  9      5.45 
## 
##          NGOs, CSOs                6      3.64 
## 
##           Awareness                6      3.64 
## 
## Comment made in other context      4      2.42 
## 
##           Research                 1      0.61 
## -----------------------------------------------</code></pre>
<p>This image is saved in Dropbox as <code>figures/fig_reasons_for_tip_mention.pdf</code> (and <code>.png</code> too).</p>
<p><img src="chapter_3_blanks_files/figure-html/unnamed-chunk-22-1.png" title="" alt="" width="672" /></p>
</div>
</div>
<div id="us-embassy-activity" class="section level1">
<h1>US embassy activity</h1>
<p>Which countries or embassies have been the <em>most</em> active?</p>
<pre><code>## Source: local data frame [40 x 4]
## 
##             clean total       prop prop.nice
##             (chr) (int)      (dbl)     (chr)
## 1   United States   188 0.70149254     70.1%
## 2            None    16 0.05970149      6.0%
## 3  European Union    14 0.05223881      5.2%
## 4             All    12 0.04477612      4.5%
## 5     Switzerland     8 0.02985075      3.0%
## 6       Australia     7 0.02611940      2.6%
## 7           Italy     7 0.02611940      2.6%
## 8  United Kingdom     7 0.02611940      2.6%
## 9     Netherlands     6 0.02238806      2.2%
## 10         Norway     6 0.02238806      2.2%
## ..            ...   ...        ...       ...</code></pre>
<pre><code>## [1] 39</code></pre>
<p>Over the last 10–15 years, has the United States or its embassy been active in the fight against human trafficking in X?</p>
<pre><code>## .
##         No        Yes Don&#39;t know 
##         39        344        150</code></pre>
<pre><code>## .
##         No        Yes Don&#39;t know 
## 0.07317073 0.64540338 0.28142589</code></pre>
<p>Side-by-side graph of active countries + most active countries (this image is saved in Dropbox as <code>figures/fig_embassies_mentioned.pdf</code> (and <code>.png</code> too)).</p>
<p><img src="chapter_3_blanks_files/figure-html/unnamed-chunk-26-1.png" title="" alt="" width="672" /></p>
<div id="actual-text-5" class="section level3">
<h3>Actual text</h3>
<blockquote>
<p>The rate at which the US embassy was mentioned as active was far greater than that of any other embassy mentioned. (TODO: There’s a paragraph about these exact numbers in the article…).</p>
</blockquote>
</div>
</div>
<div id="us-embassy-importance" class="section level1">
<h1>US embassy importance</h1>
<p>Raw counts, percents, and sum of “Most important” and “Somewhat important” percents:</p>
<pre><code>## .
##     Most important actor Somewhat important actor   Not an important actor               Don&#39;t know 
##                      139                      182                       68                      133 
## .
##     Most important actor Somewhat important actor   Not an important actor               Don&#39;t know 
##                0.2662835                0.3486590                0.1302682                0.2547893</code></pre>
<pre><code>## [1] 0.6149425</code></pre>
<p>Percent of countries where at least one NGO said the US was important:</p>
<pre><code>## [1] 0.8270677</code></pre>
<div id="actual-text-6" class="section level3">
<h3>Actual text</h3>
<blockquote>
<p>Furthermore, nearly two-thirds of NGOs said that the US had played a very important or a somewhat important role in their country. If the responses are instead broken down by country, the share of countries in which at least one NGOs attributed an important or a somewhat important role was 82.71%. (TODO: fill in other way of breaking down this data by country and whether US funding recipients (lots of this kind of stuff is in the article)).</p>
</blockquote>
</div>
</div>
<div id="us-embassy-positivity" class="section level1">
<h1>US embassy positivity</h1>
<pre><code>## 
## -------------------------------------
##   Q3.25     num    prop    prop.nice 
## ---------- ----- -------- -----------
## Don&#39;t know  36    0.1139     11.4%   
## 
##   Mixed     64    0.2025     20.3%   
## 
##  Negative    2   0.006329    0.6%    
## 
##  Positive   214   0.6772     67.7%   
## -------------------------------------</code></pre>
<div id="actual-text-7" class="section level3">
<h3>Actual text</h3>
<blockquote>
<p>Finally, if respondents indicated that the US had played an important role in their countires, the survey asked about whether the influence of the US had been positive, negative or mixed. What was most astounding was the extremely low frequency of negative replies. The vast majority was positive (214) and some were mixed (64), but only (2) said the US had played a negative role. (TODO: fill in other way of breaking down this data, by country and whether US funding recipients (lots of this kind of stuff is in the article)).</p>
</blockquote>
</div>
</div>
<div id="general-survey-details" class="section level1">
<h1>General survey details</h1>
<pre><code>## 
## ------------------
##  Countries   Freq 
## ----------- ------
##      1       415  
## 
##      2        52  
## 
##      3        10  
## 
##      4        3   
## ------------------</code></pre>
<pre><code>## 
## ---------------------
##  survey.method   num 
## --------------- -----
##    LinkedIn       3  
## 
##     Online       463 
## 
##      Phone       14  
## ---------------------</code></pre>
<div id="actual-text-8" class="section level3">
<h3>Actual text</h3>
<blockquote>
<p>Most organizations (415) chose to fill out the survey for just one country, the primary country of their advocacy work. The survey was assembled in Qualtrics and can be obtained in its entirety from the author (or is available in online appendix). To minimize frustration that might lead respondents to quit prematurely, they were free to skip any question and could move back and forth in the survey. The survey was administered via email, with the option for respondents to have a phone survey in lieu of answering it online or having a conversation in addition to the survey. Most responses (463) were obtained directly in response to the email inquiry. 14 were conducted via phone. An invitation to participate in the survey was also posted to a LinkedIn discussion group used by anti-trafficking NGOs, which yielded 3 complete responses. Each NGO in the database received two reminder emails, including respondents who started but did not finish the survey, and were provided with a link to resume their response. Additional efforts were made to reach non-responding NGOs by phone if we had very low participation from their countries.</p>
</blockquote>
</div>
</div>


</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
